import { SiteConfig, SitePaths } from "@/config/site-types";

export const siteConfig: SiteConfig = {
  title: "NeoWave App",
  description: "Generated by Arnau Gelonch & Ezequiel Rivas",
  links: {
    HOME: SitePaths.HOME,
    ABOUT: SitePaths.ABOUT,
    PRICING: SitePaths.PRICING,
    PLATFORM: SitePaths.PLATFORM,
  },
};
