export const PRICING_PLANS = [
  {
    name: "ESSENTIAL",
    price: 14.95,
    features: [
      { name: "2 charts per tab", included: true },
      { name: "5 indicators per chart", included: true },
      { name: "10K historical bars", included: true },
      { name: "20 price alerts", included: true },
      { name: "20 technical alerts", included: true },
      { name: "10 parallel chart connections", included: true },
      { name: "No ads", included: true },
      { name: "Volume profile", included: true },
      { name: "Custom timeframes", included: true },
      { name: "Custom Range Bars", included: true },
      { name: "Multiple watchlists", included: true },
      { name: "Bar Replay", included: true },
      { name: "Indicators on indicators", included: true },
      { name: "Custom Volume Profile", included: false },
      { name: "Intraday Renko, Kagi, Line Break", included: false },
      { name: "Charts based on custom formulas", included: false },
      { name: "Time Price Opportunity", included: false },
      { name: "Volume footprint", included: false },
      { name: "Auto Chart Patterns", included: false },
      { name: "Second-based alerts", included: false },
      { name: "Charts that don't expire", included: false },
      { name: "Publishing invite-only scripts", included: false },
      { name: "Second-based intervals", included: false },
      { name: "Tick-based intervals (BETA)", included: false },
      { name: "Ability to buy professional market data", included: false },
      { name: "First priority support", included: false },
    ],
  },
  {
    name: "PLUS",
    price: 29.95,
    features: [
      { name: "2 charts per tab", included: true },
      { name: "5 indicators per chart", included: true },
      { name: "10K historical bars", included: true },
      { name: "20 price alerts", included: true },
      { name: "20 technical alerts", included: true },
      { name: "10 parallel chart connections", included: true },
      { name: "No ads", included: true },
      { name: "Volume profile", included: true },
      { name: "Custom timeframes", included: true },
      { name: "Custom Range Bars", included: true },
      { name: "Multiple watchlists", included: true },
      { name: "Bar Replay", included: true },
      { name: "Indicators on indicators", included: true },
      { name: "Custom Volume Profile", included: true },
      { name: "Intraday Renko, Kagi, Line Break", included: true },
      { name: "Charts based on custom formulas", included: true },
      { name: "Time Price Opportunity", included: true },
      { name: "Volume footprint", included: true },
      { name: "Auto Chart Patterns", included: true },
      { name: "Second-based alerts", included: true },
      { name: "Charts that don't expire", included: true },
      { name: "Publishing invite-only scripts", included: true },
      { name: "Second-based intervals", included: true },
      { name: "Tick-based intervals (BETA)", included: false },
      { name: "Ability to buy professional market data", included: false },
      { name: "First priority support", included: false },
    ],
  },
  {
    name: "PREMIUM",
    price: 59.95,
    features: [
      { name: "2 charts per tab", included: true },
      { name: "5 indicators per chart", included: true },
      { name: "10K historical bars", included: true },
      { name: "20 price alerts", included: true },
      { name: "20 technical alerts", included: true },
      { name: "10 parallel chart connections", included: true },
      { name: "No ads", included: true },
      { name: "Volume profile", included: true },
      { name: "Custom timeframes", included: true },
      { name: "Custom Range Bars", included: true },
      { name: "Multiple watchlists", included: true },
      { name: "Bar Replay", included: true },
      { name: "Indicators on indicators", included: true },
      { name: "Custom Volume Profile", included: true },
      { name: "Intraday Renko, Kagi, Line Break", included: true },
      { name: "Charts based on custom formulas", included: true },
      { name: "Time Price Opportunity", included: true },
      { name: "Volume footprint", included: true },
      { name: "Auto Chart Patterns", included: true },
      { name: "Second-based alerts", included: true },
      { name: "Charts that don't expire", included: true },
      { name: "Publishing invite-only scripts", included: true },
      { name: "Second-based intervals", included: true },
      { name: "Tick-based intervals (BETA)", included: true },
      { name: "Ability to buy professional market data", included: true },
      { name: "First priority support", included: true },
    ],
  },
];
